time_sample: 0.01
# the sampling time to control the robot
slave_file_date: '20240912140410' # cut-in vertical
#TODO: the object with the skin such as lemon need spacial cutoff path
#TODO: use the lemon as the cuttingoff traj for all of objs
#clay:20240903171527
#20240906152341 cutoff lemon new, no
#20240905160707 realknife cutoff lemon
#20240905161140 realknife cutoff lemon
#20240905165224 realknife slice clay
#20240906134431 slice clay
#20240906134635 slice plasticine
#20240906134018 cutin clay
#20240909120507 cutoff lemon newnew good

#20240912133152 new cutoff lemon
#20240912135820 slaveposslice lemon
#20240912185517 slaveposslice apple
#20240912185955 slaveposslice orange
#20240912140410 slaveposcutin lemon
# for DMPs follow
traj_name: 'cutin'
# the trajectory name for recording (cutoff, cutin, slice, $dig$)
obj_name: 'banana'
# the cut object in autocut system
track_file_date: '20240912184951'
#20240912165421poscutoffbanana.npy
#20240912172445poscutoffapple.npy
#20240912170539poscutoffpear.npy
#20240912170153poscutofforange.npy
#20240912172721poscutoffkiwi.npy
#20240912173029poscutoffcucumber.npy
# real robot track the DMPs trajectory
controlled_robot_ip: '10.42.0.162'
# slave robot/ controlled robot ip
run_mode: True
# the running mode of the replan. False: sim with plot, True: real robot movej
record: True
# record the viedo when cutting
forgetting_err:
    memory_strength: 0.01
    memory_strength_rot: 0.01
    # the smaller, the stronger nonlinear
    memory_number: 50
    # the number of the memory
    to_force_coefficient: 0.085
    to_torque_coefficient: 0.05
    # the smaller, the smaller force, but can not be too large because it divide t^2
admittance_controller:
    mass: 1
#    k_pos: 3500
    k_pos: 6000
    # spring for position, use critical damping
    k_rot: 3000
    # same as k_pos, both of them can be changed, the bigger, the smaller moving
    dt: 0.01
    # same as the frequency of controlling
DMPs:
    dt: 0.01
    n_weights_per_dim: 50
    smooth_scaling: True
    new_start_pos: [-0.32831003, -0.22441479,  0.22995105,  2.91236979, -0.01258906, -0.8095211]
    new_goal_pos: [-0.23837515, -0.28937625,  0.09446688,  2.97351199, -0.18660259, -0.17417273]
    new_start_force: [-0.052, 0.050, 0.057, -0.000, -0.001, -0.001]
    new_goal_force: [-0.232, -0.790, -0.335, -0.020,  0.040, -0.017]
replan:
    contact: False
    # False: do not contact, to True: get the first time of contacting
    ft_th: 1
    # force threshold, for the first time of contacting
    o_pz: 0.0002
    # add delta_z in position for get the contact in t2 loop
    cut_class: 1
    # the class of cutting
    # 1: cut-in / cut-off, make the knife close to the ground
    # 2: cut on the surface, do not need to replan the position Z
    o_pos_dis: 0.008
    # the changing distance of the target, unit: meter
    o_rot_dis: 0.1
    # the changing distance of the target, unit: rad
    z_base: -0.01
    # the demo traj's z-base
    z_diff_th: 0.015
    # to update the z-base in t2
    f_shape_compensation_alpha: 0.7
    # the weight for force-shape compensation


