time_sample: 0.015
# the sampling time to control the robot
#slave_file_date: '20240808135415' # cut-in vertical
slave_file_date: '20240808135415' # cut-in vertical TODO: change to cut-off vertical
# for DMPs follow
track_file_date: '20240809143923'
# real robot track the DMPs trajectory
controlled_robot_ip: '10.42.0.162'
# slave robot/ controlled robot ip
forgetting_err:
    memory_strength: 0.01
    memory_strength_rot: 0.01
    # the smaller, the stronger nonlinear
    memory_number: 100
    # the number of the memory
    to_force_coefficient: 0.085
    to_torque_coefficient: 0.05
    # the smaller, the smaller force, but can not be too large because it divide t^2
admittance_controller:
    mass: 1
    k_pos: 3500
    # spring for position, use critical damping
    k_rot: 2000
    # same as k_pos, both of them can be changed, the bigger, the smaller moving
    dt: 0.01
    # same as the frequency of controlling
DMPs:
    dt: 0.01
    n_weights_per_dim: 50
    smooth_scaling: True
    new_start_pos: [-0.2575, -0.311, 0.192,  2.969, 0.152,  -0.038]
    new_goal_pos: [-0.088,  -0.321, 0.061,  3.029, -0.152, 0.562]
    new_start_force: [-0.052, 0.050, 0.057, -0.000, -0.001, -0.001]
    new_goal_force: [-0.232, -0.790, -0.335, -0.020,  0.040, -0.017]